# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6110bf293154d8d16f877749623ce6148bd9dde60028110cbe85473f6ec2c3370005158a6fd7270102de3a4c6b5ee27174a1cf587bc913ebcbd25bc31a27735c

test:
  secret_key_base: 11d85c3267edd9857430609b8c8d5853b83e4a2610f2207de26c99e7da77d3d8997ea928dc04af9be1640601fee8d5b6239d8a0bab8f1e551ef36f0ae87e8934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
